### ISSUE TITLE
Beautify the default scrollbar with `perfect-scrollbar`

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#906]

**Comment by JamesChenX** [comment]
![image](https://user-images.githubusercontent.com/44962329/148519945-324f7bd6-9966-4cf6-8f14-1c3c2165e983.png)

**Comment by JamesChenX** [comment]
To implement the feature in a simple way by just using CSS with some caveats (no transition, no support for Firefox), we won't use `perfect-scrollbar`.
```scss
/* Targets on Chrome, Edge, and Safari */
::-webkit-scrollbar {
  width: 10px;
  height: 10px;
}

::-webkit-scrollbar-track {
  background: rgb(250, 250, 250);
}

::-webkit-scrollbar-thumb {
  background: #bfbfbf;
  border-radius: 5px;
}

::-webkit-scrollbar-thumb:hover {
  background: #8c8c8c;
}
```
![image](https://user-images.githubusercontent.com/44962329/148616720-caf77e07-c143-45de-bfdc-a72778bd8be6.png)
